export const registerForm = [
  {
    id: 'firstName',
    placeholder: 'First name',
    required: true,
    type: 'text',
    label: 'First name',
  },
  {
    id: 'lastName',
    placeholder: 'Last name',
    required: true,
    type: 'text',
    label: 'Last name',
  },
  {
    id: 'email',
    placeholder: 'Email',
    required: true,
    type: 'text',
    label: 'Email',
  },
  {
    id: 'address1',
    placeholder: 'Address 1',
    type: 'text',
    label: 'Address 1',
  },
  {
    id: 'city',
    placeholder: 'City',
    type: 'text',
    label: 'City',
  },
  {
    id: 'state',
    placeholder: 'State',
    type: 'text',
    label: 'State',
  },
  {
    id: 'zip',
    placeholder: 'Zip',
    type: 'text',
    label: 'Zipcode',
  },
  {
    id: 'phone',
    placeholder: 'Phone',
    required: true,
    type: 'text',
    label: 'Phone',
  },
  {
    id: 'jobTitle',
    options: [
      '',
      'Engineer - lead',
      'Engineer - mid level',
      'Engineer - junion',
      'Engineer - front end focused',
      'Engineer - backend focused',
      'Engineer - full stack',
    ],
    placeholder: 'Please select job title',
    type: 'select',
    label: 'Job title',
  },
  {
    id: 'reason',
    placeholder: 'Describe why you are a good fit for the job you are applying for.',
    type: 'textarea',
    label: 'Note',
  },
];
